# Generated by Django 5.2 on 2025-04-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='emaail',
            new_name='email',
        ),
    ]
