# Generated by Django 5.2 on 2025-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_teacher_user_remove_user_otp_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
